using FluentAssertions;
using Hathor.Infrastructure.Auth;
using Hathor.Infrastructure.Ef;
using Hathor.Infrastructure.Sync;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Hathor.Api.Tests;

// Pull without a configured remote must short-circuit (desktop "No remote
// DB configured" message) without touching the network or the other deps.
public sealed class RemotePullTests : IAsyncLifetime
{
    private readonly string? _savedDbHost;
    private readonly List<string> _databases = [];

    public RemotePullTests()
    {
        _savedDbHost = Environment.GetEnvironmentVariable("DB_HOST");
        Environment.SetEnvironmentVariable("DB_HOST", null);
    }

    public Task InitializeAsync() => Task.CompletedTask;

    public async Task DisposeAsync()
    {
        Environment.SetEnvironmentVariable("DB_HOST", _savedDbHost);
        foreach (var db in _databases)
        {
            try { await TestPostgres.DropDatabaseAsync(db); }
            catch { }
        }
    }

    private async Task<string> CreateDatabaseAsync(string prefix)
    {
        var (connectionString, database) = await TestPostgres.CreateDatabaseAsync(prefix);
        _databases.Add(database);
        return connectionString;
    }

    [Fact]
    public async Task PullSongs_WithoutRemote_ReturnsUnavailable()
    {
        var svc = new RemotePullService(null!, null!, null!, new RemoteDbOptions(), NullLogger<RemotePullService>.Instance);
        var result = await svc.PullSongsAsync(Guid.NewGuid());
        result.Added.Should().Be(0);
        result.DownloadsStarted.Should().Be(0);
        result.Message.Should().Contain("No remote DB configured");
    }

    [Fact]
    public async Task PullPodcasts_WithoutRemote_ReturnsUnavailable()
    {
        var svc = new RemotePullService(null!, null!, null!, new RemoteDbOptions(), NullLogger<RemotePullService>.Instance);
        var result = await svc.PullPodcastsAsync(Guid.NewGuid());
        result.Added.Should().Be(0);
        result.DownloadsStarted.Should().Be(0);
        result.Message.Should().Contain("No remote DB configured");
    }

    [Fact]
    public void RemoteDbOptions_WithoutHost_HasNoConnectionString()
    {
        new RemoteDbOptions().ConnectionString().Should().BeNull();
    }

    // EnsureMigrated never alters existing databases destructively: a
    // pre-TargetFile Download_Queue must gain the column (reruns no-op).
    [Fact]
    public async Task EnsureDatabaseCreated_AddsTargetFileToOldDatabase()
    {
        var cs = await CreateDatabaseAsync("hathor_ensure");
        await TestPostgres.ExecuteAsync(cs,
            "CREATE TABLE \"Download_Queue\" (\"Id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"Qid\" text)");
        using (var db = new HathorDbContext(TestPostgres.Options(cs)))
            InfrastructureServiceExtensions.EnsureDatabaseCreated(db);
        (await TestPostgres.ColumnNamesAsync(cs, "Download_Queue")).Should().Contain("TargetFile");
        using (var db = new HathorDbContext(TestPostgres.Options(cs)))
            InfrastructureServiceExtensions.EnsureDatabaseCreated(db);
    }

    // Full legacy bridge: an EnsureCreated-era database (tables, no
    // history, no Sessions, no TargetFile) migrates into a Sessions-capable
    // database — the exact 'no such table: Sessions' failure from prod.
    [Fact]
    public async Task EnsureDatabaseCreated_BridgesLegacyDatabase()
    {
        var cs = await CreateDatabaseAsync("hathor_legacy");
        await TestPostgres.ExecuteAsync(cs,
            "CREATE TABLE \"Songs\" (\"UserId\" uuid NOT NULL, \"File\" text NOT NULL, \"Title\" text NOT NULL, PRIMARY KEY (\"UserId\", \"File\"))");
        await TestPostgres.ExecuteAsync(cs,
            "CREATE TABLE \"Download_Queue\" (\"Id\" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"Qid\" text)");
        List<string> migrations;
        using (var probe = new HathorDbContext(TestPostgres.Options(cs)))
            migrations = probe.GetService<IMigrationsAssembly>()
                .Migrations.Keys.OrderBy(k => k, StringComparer.Ordinal).ToList();
        using (var db = new HathorDbContext(TestPostgres.Options(cs)))
        {
            InfrastructureServiceExtensions.EnsureDatabaseCreated(db);
            db.Sessions.Add(new Hathor.Domain.Entities.Session
            {
                Id = Guid.NewGuid(),
                UserId = Guid.NewGuid(),
                RefreshTokenHash = "abc",
                CreatedAtUtc = DateTime.UtcNow,
                ExpiresAtUtc = DateTime.UtcNow.AddHours(1),
                LastUsedAtUtc = DateTime.UtcNow,
            });
            db.SaveChanges();
        }
        // The bridge builds the current schema, so every migration it
        // already built is stamped (Migrate() then has nothing to replay).
        (await TestPostgres.TextsAsync(cs, "SELECT \"MigrationId\" FROM \"__EFMigrationsHistory\""))
            .Should().BeEquivalentTo(migrations);
        (await TestPostgres.ColumnNamesAsync(cs, "Download_Queue")).Should().Contain("TargetFile");
        // Later-migration columns land on legacy tables too.
        (await TestPostgres.ColumnNamesAsync(cs, "Lyrics")).Should().Contain("OffsetMs");
        using (var db = new HathorDbContext(TestPostgres.Options(cs)))
            InfrastructureServiceExtensions.EnsureDatabaseCreated(db);
    }

    // Poisoned state: history claims InitialCreate but Sessions is missing
    // (interrupted earlier bridge / failed Migrate). Must repair, not skip.
    [Fact]
    public async Task EnsureDatabaseCreated_RepairsStampedButIncompleteDatabase()
    {
        var cs = await CreateDatabaseAsync("hathor_poison");
        string initial;
        using (var probe = new HathorDbContext(TestPostgres.Options(cs)))
            initial = probe.GetService<IMigrationsAssembly>()
                .Migrations.Keys.OrderBy(k => k, StringComparer.Ordinal).First();
        await TestPostgres.ExecuteAsync(cs,
            "CREATE TABLE \"Songs\" (\"UserId\" uuid NOT NULL, \"File\" text NOT NULL, \"Title\" text NOT NULL, PRIMARY KEY (\"UserId\", \"File\"))");
        await TestPostgres.ExecuteAsync(cs,
            "CREATE TABLE \"__EFMigrationsHistory\" (\"MigrationId\" character varying(150) NOT NULL PRIMARY KEY, \"ProductVersion\" character varying(32) NOT NULL)");
        await TestPostgres.ExecuteAsync(cs,
            $"INSERT INTO \"__EFMigrationsHistory\" (\"MigrationId\", \"ProductVersion\") VALUES ('{initial}', '9.0.11')");
        using (var db = new HathorDbContext(TestPostgres.Options(cs)))
        {
            InfrastructureServiceExtensions.EnsureDatabaseCreated(db);
            db.Sessions.Add(new Hathor.Domain.Entities.Session
            {
                Id = Guid.NewGuid(),
                UserId = Guid.NewGuid(),
                RefreshTokenHash = "xyz",
                CreatedAtUtc = DateTime.UtcNow,
                ExpiresAtUtc = DateTime.UtcNow.AddHours(1),
                LastUsedAtUtc = DateTime.UtcNow,
            });
            db.SaveChanges();
        }
    }

    [Fact]
    public async Task PushSongs_WithoutRemote_ReturnsUnavailable()
    {
        var svc = new RemotePushService(null!, new RemoteDbOptions(), NullLogger<RemotePushService>.Instance);
        var result = await svc.PushSongsAsync(Guid.NewGuid());
        result.Rows.Should().Be(0);
        result.Message.Should().Contain("No remote DB configured");
    }

    [Fact]
    public async Task PushPodcasts_WithoutRemote_ReturnsUnavailable()
    {
        var svc = new RemotePushService(null!, new RemoteDbOptions(), NullLogger<RemotePushService>.Instance);
        var result = await svc.PushPodcastsAsync(Guid.NewGuid());
        result.Rows.Should().Be(0);
        result.Message.Should().Contain("No remote DB configured");
    }
}
